# Generated by Django 4.1.7 on 2023-04-03 11:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontroler',
            name='introduction_descc',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='homepagecontroler',
            name='detection_desc',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepagecontroler',
            name='introduction_desc',
            field=models.CharField(default='', max_length=250),
        ),
    ]
