# Generated by Django 4.1.7 on 2023-04-03 11:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepagecontroler_introduction_descc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontroler',
            name='introduction_descc',
        ),
        migrations.AlterField(
            model_name='homepagecontroler',
            name='detection_desc',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='homepagecontroler',
            name='introduction_desc',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
